---
title: "Objective 4 - Analysis Plan"
date: "Last Updated: `r format(Sys.Date(), format='%B %d %Y')`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##### Cohort(s)
Incident Cases

##### Outcomes / Endpoint(s)
Major Adverse Cardiac Events (Major Bleeding, Systemic Embolism, Hemorrhagic Stroke, MI, All-cause mortality)

##### Planned Analyses
1. Describe rates of MACE at 30 days, 1 year, and 3 years.
2. KM + Cox Proportional Hazards model
   *	Option 1: Fixed exposure – Fix exposure to drug initiated at index diagnosis.
     * Pros: Simple
     * Cons: Ignores group changes, would likely need to reduce the length of follow-up
   *	Option 2: Time varying exposure – Allow exposure to vary between groups (Warfarin, NOAC, no OAC)
     * 	Pros: Takes into account group changes, allows for longer follow-up
     * 	Cons: Increased complexity in interpretation and implementation
3. Model Diagnostics
   *	Proportional Hazards Assumption
     * 	KM Curves
     * 	Supremum Test
     * 	Log-log plots
   *	Linearity + Additivity
     * 	Martingale Residuals

##### Planned Figures
1. Kaplan-Meier curves by Age Category, Sex, and SES
2. Forest Plot of unadjusted and adjusted Hazard ratios for MACE

##### Planned Tables
1. Number of events, composite endpoint and individual components, by Age, Sex, and SES at 30 day, 1 year and 3 years with 95% confidence intervals
2. Unadjusted and adjusted hazard ratios with 95% confidence intervals


##### Optional Analyses


