---
title: "Objective 2 - Analysis Plan"
date: "Last Updated: `r format(Sys.Date(), format='%B %d %Y')`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##### Cohort(s)
1. Incident Cohort
2. Prevalent Cohort

##### Outcomes / Endpoint(s) 
1. Time to first switch.
2. Number of switches. 
3. Proportion of patients with NOAC and Warfarin who switch drugs during follow-up.


##### Planned Analyses
1.	Model time to first switch using cox proportion hazards model.
2.	Compare number of switches between groups.
3.  Proportion of patients initiated on Warfarin to who switch to NOAC
    * Proportion of prevalent cases who switch from Warfarin to NOAC each year.
4.  Predictors of switching from Warfarin to NOAC
    * Logistic regression model

##### Planned Figures
1.	Forest plot of unadjusted and adjusted hazard ratios for time to first switch. 
2.	Kaplan Meier curves for time to first switch

##### Planned Tables
1.	HR with 95% confidence intervals
2.	Proportion of patients who switch from either Warfarin or NOAC.


##### Optional Analyses






