---
title: "Objective 1: Trends and Uptake - Analysis Plan"
date: "Last Updated: `r format(Sys.Date(), format='%B %d %Y')`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##### Cohort(s)
1. Prevalant AF Cases (Burden of Disease)
2. Incident AF Cases between January 2012 to 2016 (NOAC Uptake)

##### Exclusions:
1. Burden of Disease Cohort
    * Reversible causes of AF (Cardiac Surgery, Pneumonia, Hyperthyroidism, Pregnancy)
    * Age Range?
2. OAC Uptake 
    * Other indications for OAC (Mechanical Heart Valve, Valvular Heart Surgery, Systemic Embolization)
    * CHADSVASC <=1 
    * Survived and remained in province for up to 10,30,90 days to determine initial drug therapy
    
Hip or Knee artheroplasty? https://academic.oup.com/eurheartj/article/38/12/899/2931992
PE/DVT (Not sure if this is encompassed in "Systemic Embolization")

    
##### Outcomes / Endpoint(s)
1. First prescription after diagnosis of AF within 10,30, or 90 days of diagnosis. (OAC, NOAC, NO OAC)

##### Planned Analyses
1.  Compute incidence and prevalence of AF.
    * Prevalence defined as cumulative incidence from 2005 or from X years prior.
    * Crude and direct age/sex standardized rates
2.  Calculate proportion of AF patients who received OAC before and after NOAC introduction. (No OAC vs Warfarin)
    * Describe trend in proportion of patients initiating OAC each year among incident cases.
    * Describe trend in proportion of patients utilizing OAC each year among prevalent cases.
    * Test for Trend (Cochran–Armitage)
4. 	Describe incident AF Cohort stratified by age groups, sex, and SES 
    *	χ2 Test, t-test, ANOVA for differences in baseline characteristics and concomitant medications where appropriate
    *	Test for Trend (Cochran–Armitage)
5.	Prescription initiation pattern over time (NO OAC vs. VKA vs. NOAC, and NOAC Specific) in incident cohort.
    *	Test for trend (Cochran–Armitage)
6.	Compare trends by Age, Sex, and SES in incident cohort 
    *	Graphical comparisons.
7.  Explore factors associated with initial drug prescription using a logistic regression model. 
    *	Option 1: Multinomial logistic model with No OAC, VKA, NOAC as outcome + Create models pre/post introduction of NOAC to compare ORs.
    * Option 2: Limit to those receiving OAC. Binary outcome of VKA  or NOAC
    * Option 3: 3 Models comparing each specific NOAC to VKA.


##### Planned Figures
1. Flowchart showing breakdown by Age, Sex, SES after exclusions
2. Number of incident AF cases by year, prevalence over time.
3. Percentage initiated on OAC over time (2005 to 2016).
4. Percentage initiated on each drug over time, Warfarin vs NOAC (All), and NOAC by Type. Repeat overall, age, sex, and SES. (Trends in incident cases)
5. Forest plot of unadjusted and adjusted odds ratios for initial drug prescription.

##### Planned Tables
1.	Baseline characteristics by age groups
2.	Baseline characteristics by sex groups 
3.	Baseline characteristics by SES groups 
4.	Baseline characteristics by initial treatment. 
    * Warfarin vs NOAC and/or Warfarin vs specific NOACs.

##### Optional Analyses
1.  Describe changes to cohort (baseline characteristics, medications etc.) over time.
2.  Describe dosages of initiated medication (i.e. low vs high in dabigatran)
3.  OAC Uptake as a function of CHADSVASC, distribution of prescription type as well.
4.  Give not initially prescribed an OAC, how many cases were eventually prescribed within 1, 2, 3 years
5.  After introduction of NOACs does OAC Uptake increase?

##### Limitations
1. Cannot define ASA use.
2. Unable to verify AF with ECG Data. Misclassification bias.
3. Under coding of AF in out-patient physician claims (427 vs 4273)
4. No INR data for HAS-Bled, missing BMI and ethnicity, smoking/alcohol consumption will be underreported. Hypertension and comorbidities under-coded. 

#### Questions
1. Do Canadian guidelines discourage the use of ASA alone in management of stroke risk? European guidelines do, American Guidelines do not (As of 2017, https://doi.org/10.4414/smw.2017.14410)




