---
title: "AB2C Datasets"
date: "Last Updated: `r format(Sys.Date(), format='%B %d %Y')`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#### Raw Datasets
#####Location: R:/SAS Data/Raw_Data

#####Libname: Raw_Data

|Dataset|Description|Variables|Notes|
|---|---|---|---|
|Demographics|Demographics data from Registry File|DOB, SEX||
|DAD|Hospitalizations datasets|||
|Deaths|Death Dates|||
|Census_GEO|Census Indicators (SES)|QAIPPE, DAIPPE||
|Dinpin_List|All medications extracted|||
|Cohort_Dinpin_List|Medications used for cohort definition|||
|NACRS|NACRS Data|||
|Pnet_dsp_clm|Medications dispensed|||
|pnt_hlth_rpt|Health Products detail|||
|Registry|BC Registration dataset|||


#### Processed Datasets
#####Location: R:/SAS Data/

#####Libname: Data

|Dataset|Description|Variables|Notes|
|---|---|---|---|
|Demographics|Patient demogs from Registry and Consolidation datasets|DOB, SEX, Death Date||
|BCResidency93dgap|BC Residency time frames|Startdate, Enddate|Up to a 93 day gap in coverage is acceptable for continous registration.|
|MSP_Manip|Manipulated MSP Data|Service Date, Comorbidities||
|Hosp_comorb_index|Manipulated DAD Data|Admission date, separation date, comorbidities| Comorbidities are defined as prior to admission|
|Hosp_comorb_pre|Manipulated DAD Data|Admission date, separation date, comorbidities| Comorbidities are defined as anytime prior or during admission|
|Outcomes| Outcomes identified in DAD Data| Admission Date, Separation date, outcome indicators||
|PharmaNet_Manip||||
|NACRS_Manip|Manipulated NACRS data|Admission date, comorbidities||
|Cohort_Prevalent|Prevalent Cohort|Diagnosis Date, Source, Criteria||
